# Generated by Django 2.2.14 on 2022-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSGApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
        migrations.AlterModelTable(
            name='uploadform',
            table='hubenergy_upload_log',
        ),
    ]
