# Generated by Django 2.2.14 on 2022-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSGApp', '0002_auto_20220525_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
